config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'authentications', to: 'authentications#show'
  get 'authentications/auth'

  resources :users, only:[:show, :edit, :update]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'leaderboards/:board/:filter', to: 'leaderboards#show', as: :leaderboards
  get 'leaderboards/custom_filter'
  # get 'organic-search-leaderboards/:board', to: 'leaderboards#show', as: :organic_search_leaderboards
  # get 'social-leaderboards/:board', to: 'leaderboards#show_social', as: :social_leaderboards
  # get 'email-leaderboards/:board', to: 'leaderboards#show_email', as: :email_leaderboards
  # get 'direct-leaderboards/:board', to: 'leaderboards#show_direct', as: :direct_leaderboards
  # get 'paid-leaderboards/:board', to: 'leaderboards#show_paid', as: :paid_leaderboards

  root to: "leaderboards#show", board: "mainboard", filter: "this_month"



end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  before_action :authenticate_user!, :only => [:auth, :api_update]


  def show

    @user = current_user
  end

  def auth

    check_data
    UserApiCallJob.perform_later(current_user)

    redirect_to root_path

  end


  private

  def check_data
    if !current_user.data
      current_user.update(view_id: params[:view_id], first_time: true)
    else
      current_user.update(view_id: params[:view_id], first_time: false)
    end
  end

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper

end

app/views/authentications/_auth_form.html.erb
<% if !current_user.view_id %>

  <%=form_with url: authentications_auth_path, :method => "get", :class => 'ui form', :id => 'auth-form' do |form|%>
    <%= form.text_field :view_id, :placeholder => "Provide your view id here" %>
    <%= form.submit "Update", :class => 'ui button' %>
  <%end%>

<%else%>

  <%= form_with model: @user, :class => 'ui form', :id => 'auth-update-form' do |form|%>
    <%= form.text_field :view_id%>
    <%= form.submit "Update", :class => 'ui button'%>
  <%end%>

<%end%>

app/views/authentications/_auth_header.html.erb
<h1 class="ui header">
  <%if current_user.view_id%>
    <h2>If you like to update your View ID please replace the ID below and update</h2>

  <%else%>

    <h2>Please provide your Google Analytic View ID to connect and update</h2>
  <%end%>
</h1>

app/views/authentications/show.html.erb
<div class="ui two column centered grid">
  <div class="column">
    <%= render :partial => "auth_header"%>
  </div>

</div>
<div class="ui two column centered grid">
  <div class="column">
    <%= render :partial => "auth_form"%>
  </div>

</div>