config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'authentications', to: 'authentications#show'
  get 'authentications/auth'

  resources :users, only:[:show, :edit, :update]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'leaderboards/:board/:filter', to: 'leaderboards#show', as: :leaderboards
  get 'leaderboards/custom_filter'
  # get 'organic-search-leaderboards/:board', to: 'leaderboards#show', as: :organic_search_leaderboards
  # get 'social-leaderboards/:board', to: 'leaderboards#show_social', as: :social_leaderboards
  # get 'email-leaderboards/:board', to: 'leaderboards#show_email', as: :email_leaderboards
  # get 'direct-leaderboards/:board', to: 'leaderboards#show_direct', as: :direct_leaderboards
  # get 'paid-leaderboards/:board', to: 'leaderboards#show_paid', as: :paid_leaderboards

  root to: "leaderboards#show", board: "mainboard", filter: "this_month"



end

app/views/shared/_navigation.html.erb
<div class="ui huge stackable menu navbar">
  <%= link_to "Main Leaderboard", leaderboards_path(:board => "mainboard", :filter => "this_month"), class: "item #{'active' if @board_name == 'mainboard'}" %>
  <%= link_to "Organi Search Leaderboard", leaderboards_path(:board => "organic_search", :filter => "this_month"), class: "item #{'active' if @board_name == 'organic_search'}" %>
  <%= link_to "Social Leaderboard", leaderboards_path(:board => "social", :filter => "this_month"), class: "item #{'active' if @board_name == 'social'}" %>
  <%= link_to "Email Leaderboard", leaderboards_path(:board => "email", :filter => "this_month"), class: "item #{'active' if @board_name == 'email'}" %>
  <%= link_to "Direct Leaderboard", leaderboards_path(:board => "direct", :filter => "this_month"), class: "item #{'active' if @board_name == 'direct'}" %>
  <%= link_to "Paid Leaderboard", leaderboards_path(:board => "paid", :filter => "this_month"), class: "item #{'active' if @board_name == 'paid'}" %>

  <div class="right menu">
    <% if !user_signed_in? %>
      <%= link_to "Authenticate", user_google_oauth2_omniauth_authorize_path, :class => "ui item "%>
    <%else%>


      <%= link_to "Update Data", authentications_path, :class => "ui item" %>


      <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "ui item" %>
    <%end%>

  </div>
</div>

app/views/shared/_notifications.html.erb
<% if notice || alert %>
  <div class="ui message">
    <i class="close icon"></i>
    <div class="header">
      <% if notice %>
        Notice
      <%end%>
      <% if alert %>
        Alert
      <%end%>
    </div>
    <p><%= notice %></p>
    <p><%= alert %></p>
  </div>
<% end %>

<div id="push" class="ui message transition hidden">
<i class="close icon"></i>
<div class="header">
</div>
<p></p>

</div>