config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'authentications', to: 'authentications#show'
  get 'authentications/auth'

  resources :users, only:[:show, :edit, :update]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'leaderboards/:board/:filter', to: 'leaderboards#show', as: :leaderboards
  get 'leaderboards/custom_filter'
  # get 'organic-search-leaderboards/:board', to: 'leaderboards#show', as: :organic_search_leaderboards
  # get 'social-leaderboards/:board', to: 'leaderboards#show_social', as: :social_leaderboards
  # get 'email-leaderboards/:board', to: 'leaderboards#show_email', as: :email_leaderboards
  # get 'direct-leaderboards/:board', to: 'leaderboards#show_direct', as: :direct_leaderboards
  # get 'paid-leaderboards/:board', to: 'leaderboards#show_paid', as: :paid_leaderboards

  root to: "leaderboards#show", board: "mainboard", filter: "this_month"



end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :check_page_params

  def show

    board = "#{params[:board]}_#{params[:filter]}"
    @board_name = params[:board]
    @lb = Boards.leaderboard(board)

    @entries = entry_service.execute(query_options(board))

    respond_to do |format|
      format.html do
        paginate(query_options(board))
      end

    end


  end

  def custom_filter

    custom_api_call(params[:start_date].to_date.to_s, params[:end_date].to_date.to_s, params[:board])
    redirect_to leaderboards_path(board: params[:board], filter: "custom")
  end

  private

  def entry_service
    Boards::GetAllService.new
  end

  def paginate(options = {})
      pager = Kaminari.paginate_array(
        @entries,
        total_count: @lb.total_members)
      @page_array = pager.page(options[:page]).per(options[:limit])

  end

  def check_page_params
    @page = params[:page] || nil

    if @page
      @drop = 0
    else
      @drop = 1
    end
  end

  def custom_api_call(start_date, end_date, board_type)
    @users = User.all
    @users.each do |user|
      CustomApiCallJob.perform_later(user, start_date, end_date, board_type)
      # api = user.custom_api_call(start_date, end_date)
      # user.update_custom_leaderboard(api, board_type)
    end

  end


end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper


end

app/views/leaderboards/shared/_sort.html.erb
<div class="ui small menu filter">

  <div class="right menu default-filter">
    <div class="header item">Sort By</div>

    <%= link_to "This Week", "this_week", class: "item" %>
    <%= link_to "Last Week", "last_week", class: "item" %>
    <%= link_to "This Month", "this_month", class: "item" %>
    <%= link_to "Last Month", "last_month", class: "item" %>
    <a class="item custom-filter-button">
      Custom Filter
    </a>
  </div>
  <div class="right menu custom-filter">
    <div class="item">
      <i class="close icon"></i>
    </div>

    <div class="item custom-filter-form">
      <%= form_with url: leaderboards_custom_filter_url, method: :get, id: "filter-form", class: "ui form" do |form| %>
        <%= form.hidden_field :board, value: @board_name %> 
        <div class="fields">
          <div class="field">
            <div class="ui calendar" id="start-date">
              <div class="ui input left icon">
                <i class="calendar icon"></i>
                <%= form.text_field :start_date, placeholder: "Start Date" %>
                <!-- <input type="text" placeholder="Start Date"> -->
              </div>
            </div>
          </div>
          <div class="field">
            <div class="ui calendar" id="end-date">
              <div class="ui input left icon">
                <i class="calendar icon"></i>
                <%= form.text_field :end_date, placeholder: "End Date" %>
                <!-- <input type="text" placeholder="End Date"> -->
              </div>
            </div>
          </div>

          <div class="field">
            <%= form.submit "Filter", class: "ui button"%>
          </div>
        </div>





      <% end %>
    </div>


  </div>
</div>